PlayerIdFieldName: PlayerId
GithubRepoName: hostedvgctours
PokePasteFieldName: Paste
LoadTranslations: True
AssetsUrl: https://cdn.jsdelivr.net/gh/relderDev/vgctourhelper-resources@latest/Assets/
PokemonKeyFieldName: Pokémon
OverlayTemplate: {App}Resources\overlay.html
MoveDataFormat: CSV
PokemonAssetsFolder: Pokemon/
TypeDataFormat: CSV
PokemonAssetFieldName: Dex_Number
TypeDataFile: Colors.csv
PairingsIncludes: {App}Resources\pairings.css
MoveKeyFieldName: Move
TranslateTeamlist: False
TeamlistTemplate: {App}Resources\teamlist.html
FirstRowIsHeader: True
SaveOnExit: True
Language: It
TeamlistOutputPath: {App}Outputs\{TournamentName}\Teamlists
PokemonDataFile: Pokemon.csv
Player1Output: {App}Outputs\Stream\player1.html
TypeAssetFieldName: Type
TextDelimiter: "
GithubIncludes: {App}Resources\Repository\tournament.js {App}Resources\Repository\tournament.css {App}Resources\Repository\teamlist.css {App}Resources\Repository\pokemon.css {App}Resources\Repository\pairings.css {App}Resources\Repository\standings.css
StandingsOutput: {App}Outputs\Stream\standings.html
AbilityKeyFieldName: English
StandingsIncludes: {App}Resources\standings.css
ColumnDelimiter: ;
Player2Output: {App}Outputs\Stream\player2.html
ItemAssetFieldName: Item
AbilityDataFormat: CSV
TypeKeyFieldName: Type
GithubRepoOwner: relderDev
OverlayOutput: {App}Outputs\Stream\index.html
GithubOutputPath: {TournamentName}
DataPath: {App}Resources\Data\
ItemKeyFieldName: Number2
HeaderFromFirstRecord: True
TypeAssetsFolder: Types/
ItemDataFormat: CSV
ItemAssetsFolder: Items/
PokemonTemplate: {App}Resources\pokemon.html
ItemDataFile: Items.csv
PokemonDataFormat: CSV
TeamlistIncludes: {App}Resources\teamlist.css {App}Resources\pokemon.css
MoveDataFile: Moves.csv
TeamlistIconUrl: https://images.icon-icons.com/1893/PNG/32/clipboard_120835.png
PairingsOutput: {App}Outputs\Stream\pairings.html
AbilityDataFile: Abilities.csv